/**
 * `Env` is generated by `wrangler types` from the bindings; the secrets and
 * the optional vars are declared here because the config does not carry them.
 */
export interface AppEnv extends Env {
  /** Worker secrets in production, `.dev.vars` locally, test bindings under vitest. */
  GOOGLE_CLIENT_ID: string
  /** The OAuth client's secret; only the Worker ever holds it. */
  GOOGLE_CLIENT_SECRET: string
  MEDIA_QUOTA_BYTES?: string
  MEDIA_PUBLIC_BASE_URL?: string
}

/** 8 GiB: comfortably under R2's free allowance, so the account never bills. */
export const DEFAULT_MEDIA_QUOTA_BYTES = 8 * 1024 * 1024 * 1024

export function mediaQuotaBytes(env: AppEnv): number {
  const configured = Number(env.MEDIA_QUOTA_BYTES)
  return Number.isSafeInteger(configured) && configured > 0 ? configured : DEFAULT_MEDIA_QUOTA_BYTES
}

/** Where objects are served from: the configured base, else this Worker's own `/m`. */
export function mediaPublicBaseUrl(env: AppEnv, request: Request): string {
  const configured = env.MEDIA_PUBLIC_BASE_URL?.trim()
  const base = configured ? configured : `${new URL(request.url).origin}/m`
  return base.replace(/\/+$/, '')
}
